---
- hosts: kibana
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  tasks:
          #    - include_role:
          #        name: set-update-repo
    - include_role:
        name: install-docker-ubuntu
    - include_role:
        name: install-docker-compose
    - include_role:
        name: install-kibana-docker
